
import re
import pandas as pd

RESP_REGEXES = [
    re.compile(r"(P[0-9]+)\s+Original\s+Prompt\s+Response\s*-\s*(.+?)\s*\((?:.+?)\)", re.I),
    re.compile(r"(P[0-9]+)\s+Perturbed\s+Prompt\s+Response\s*-\s*(.+?)\s*\((?:.+?)\)", re.I),
    re.compile(r"\bResponse\b\s*-\s*(.+?)\s*(?:\(|$)", re.I),
]
SCORE_REGEX = re.compile(r"^Score\s*\(.*?\).*?Generated by\s+(.+?)\s*(?:\(|$).*?Assessed\s+by\s+(.+)$", re.I)
RUBRIC_COL_REGEX = re.compile(r"Rubric.*Level Definitions", re.I)

def clean(text: str) -> str:
    return re.sub(r"\s+", " ", str(text)).strip()

def detect_main_sheet(xl: pd.ExcelFile) -> str:
    sizes = []
    for s in xl.sheet_names:
        try:
            df = xl.parse(s, nrows=2)
            sizes.append((s, df.shape[1]))
        except Exception:
            pass
    sizes.sort(key=lambda x: x[1], reverse=True)
    return sizes[0][0] if sizes else xl.sheet_names[0]

def scan_columns(df: pd.DataFrame) -> pd.DataFrame:
    cols = [clean(c) for c in df.columns]
    records = []
    for idx, col in enumerate(cols):
        role = None; model = None; assessor = None; ptag=None
        m_score = SCORE_REGEX.search(col)
        if m_score:
            role = "score"
            model = m_score.group(1).strip()
            assessor = m_score.group(2).strip()
        else:
            for rgx in RESP_REGEXES:
                m = rgx.search(col)
                if m:
                    if len(m.groups())==2 and m.group(1).upper().startswith("P"):
                        ptag = m.group(1).upper()
                        model = m.group(2).strip()
                        role = "response_perturbed" if "perturb" in col.lower() else "response_original"
                    else:
                        role = "response"
                        model = m.group(1).strip()
                    break
        if role:
            lc = col.lower()
            if any(x in lc for x in [
                "track (tools on/off)",
                "gen config (temp/top-p/seed)",
                "run id (uuid)",
                "timestamp (iso-8601)"
            ]):
                continue
            records.append({
                "col_index": idx,
                "column": col,
                "role": role,
                "ptag": ptag or "",
                "model": model or "",
                "assessor": assessor or ""
            })
    import pandas as _pd
    return _pd.DataFrame(records)

def find_rubric_columns(df: pd.DataFrame):
    rubs = []
    for c in df.columns:
        if RUBRIC_COL_REGEX.search(clean(c)):
            rubs.append(c)
    return rubs
